# Generated by Django 6.1.1 on 2026-10-02 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_officertransfer'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('masters', '0002_seed_masters'),
        ('pumps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='pumps.pump'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'PUMP_OPERATOR'), _negated=True), ('pump__isnull', False), _connector='OR'), name='pump_operator_needs_pump'),
        ),
    ]
