# Generated by Django 6.1.1 on 2026-10-02 03:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_officertransfer'),
        ('masters', '0002_seed_masters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('POLICE', 'Police pump'), ('TIE_UP', 'Tie-up bunk')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('opening_hours', models.CharField(default='24/7', max_length=60)),
                ('sells_petrol', models.BooleanField(default=True)),
                ('sells_diesel', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pumps', to='masters.district')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pumps', to='accounts.unit')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PumpTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], max_length=10)),
                ('capacity_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('current_stock_litres', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('low_stock_threshold_litres', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=9)),
                ('low_stock_alerted', models.BooleanField(default=False)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='pumps.pump')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pump',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_pump_name_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='pump',
            constraint=models.CheckConstraint(condition=models.Q(('sells_petrol', True), ('sells_diesel', True), _connector='OR'), name='pump_sells_a_fuel'),
        ),
        migrations.AddConstraint(
            model_name='pumptank',
            constraint=models.UniqueConstraint(fields=('pump', 'fuel_type'), name='one_tank_per_fuel_per_pump'),
        ),
    ]
