# Generated by Django 6.1.1 on 2026-10-02 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MEASUREMENT', 'Morning measurement'), ('TANKER_RECEIPT', 'Tanker receipt'), ('DISPENSE', 'Fill')], max_length=20)),
                ('litres', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock_before', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stock_after', models.DecimalField(decimal_places=2, max_digits=9)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='pumps.pumptank')),
            ],
            options={
                'verbose_name_plural': 'stock entries',
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
