# Generated by Django 6.1.1 on 2026-10-04 05:49

from django.db import migrations, models


def measurements_to_openings(apps, schema_editor):
    """There is no daily measurement any more: the measurements kept so far set the stock, so they are openings."""
    apps.get_model("pumps", "StockEntry").objects.filter(kind="MEASUREMENT").update(kind="OPENING")


def openings_to_measurements(apps, schema_editor):
    apps.get_model("pumps", "StockEntry").objects.filter(kind="OPENING").update(kind="MEASUREMENT")


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0002_stockentry'),
    ]

    operations = [
        migrations.RunPython(measurements_to_openings, openings_to_measurements),
        migrations.AlterField(
            model_name='stockentry',
            name='kind',
            field=models.CharField(choices=[('OPENING', 'Opening stock'), ('TANKER_RECEIPT', 'Tanker receipt'), ('DISPENSE', 'Fill')], max_length=20),
        ),
    ]
