# Generated by Django 6.1.1 on 2026-10-04 06:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_pump_user_pump_operator_needs_pump'),
        ('fleet', '0003_vehicle_odometer_alert_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_particulars', models.TextField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=120)),
                ('last_point_at', models.DateTimeField(blank=True, null=True)),
                ('last_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_accuracy_m', models.FloatField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_trips', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_trips', to='accounts.unit')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_trips', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('heading_deg', models.FloatField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tracking.dutytrip')),
            ],
            options={
                'ordering': ['recorded_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dutytrip',
            index=models.Index(fields=['unit', 'ended_at'], name='trip_unit_open'),
        ),
        migrations.AddConstraint(
            model_name='dutytrip',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('driver',), name='one_open_trip_per_driver'),
        ),
        migrations.AddConstraint(
            model_name='locationpoint',
            constraint=models.UniqueConstraint(fields=('trip', 'recorded_at'), name='one_point_per_moment'),
        ),
    ]
