# Generated by Django 6.1.1 on 2026-10-02 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=15, unique=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('JEEP', 'Jeep'), ('MOTORCYCLE', 'Motorcycle'), ('VAN', 'Van'), ('BUS', 'Bus'), ('TRUCK', 'Truck'), ('OTHER', 'Other')], max_length=20)),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year_of_manufacture', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], max_length=10)),
                ('tank_capacity_litres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chassis_number', models.CharField(blank=True, max_length=30)),
                ('engine_number', models.CharField(blank=True, max_length=30)),
                ('odometer_at_onboarding_km', models.PositiveIntegerField(default=0)),
                ('monthly_fuel_limit_litres', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('service_interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('service_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('TERMINATION_PENDING', 'Termination waiting for PTO'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='accounts.unit')),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('OFFICER', 'Officer'), ('DRIVER', 'Driver')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('kind', 'OFFICER')), fields=('vehicle',), name='one_current_officer_per_vehicle'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('kind', 'DRIVER')), fields=('vehicle',), name='one_current_driver_per_vehicle'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('kind', 'DRIVER')), fields=('person',), name='one_current_vehicle_per_driver'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('vehicle', 'person'), name='no_duplicate_current_link')],
            },
        ),
    ]
