# Generated by Django 6.1.1 on 2026-10-02 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('pumps', '0002_stockentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The first day of the month the extra fuel is for.')),
                ('litres', models.DecimalField(decimal_places=2, max_digits=7)),
                ('approved_by', models.CharField(max_length=120)),
                ('letter', models.FileField(upload_to='letters/%Y/%m/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FuelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel')], max_length=10)),
                ('litres_requested', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_emergency', models.BooleanField(default=False)),
                ('emergency_reason', models.TextField(blank=True)),
                ('pin', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('ISSUED', 'PIN issued'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ISSUED', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('failed_pin_attempts', models.PositiveSmallIntegerField(default=0)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('litres_filled', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('emergency_litres', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('emergency_status', models.CharField(choices=[('NONE', 'Not an emergency'), ('PENDING', 'Waiting for MTO'), ('ALLOWED', 'Allowed — counted against additional quota')], default='NONE', max_length=10)),
                ('emergency_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('duty_particulars', models.TextField(blank=True)),
                ('duty_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duty_overdue_notified', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_requests', to=settings.AUTH_USER_MODEL)),
                ('emergency_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fills', to='pumps.pump')),
                ('stock_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_request', to='pumps.stockentry')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_requests', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['vehicle', 'status', 'filled_at'], name='fuelreq_vehicle_status_filled')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ISSUED')), fields=('vehicle',), name='one_open_request_per_vehicle')],
            },
        ),
    ]
