# Generated by Django 6.1.1 on 2026-10-02 08:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
        ('pumps', '0002_stockentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BunkStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The first day of the month the statement is for.')),
                ('petrol_litres', models.DecimalField(decimal_places=2, max_digits=9)),
                ('diesel_litres', models.DecimalField(decimal_places=2, max_digits=9)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('DISPUTED', 'Disputed')], default='SUBMITTED', max_length=10)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='pumps.pump')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', '-submitted_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('pump', 'month'), name='one_statement_per_pump_per_month'), models.CheckConstraint(condition=models.Q(('petrol_litres__gte', 0), ('diesel_litres__gte', 0)), name='statement_litres_not_negative')],
            },
        ),
    ]
