# Generated by Django 6.1.1 on 2026-10-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0004_statement_periods_required'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bunkstatement',
            name='statement_litres_not_negative',
        ),
        migrations.RemoveConstraint(
            model_name='bunkstatement',
            name='statement_period_in_order',
        ),
        migrations.DeleteModel(
            name='BunkStatement',
        ),
    ]
